# Generated by Django 3.2.4 on 2021-07-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discout',
            new_name='discount',
        ),
    ]
